improve Ride entity
JavaAppforFuture/oskmanager-backend pull request #14
Opened 2021-02-18 22:29 UTC by idzikdev

improved Ride entity

2021-02-18 22:37 UTC, hanna-halman approved these changes

2021-02-19 18:10 UTC, mklasicki approved these changes

2021-02-19 19:33 UTC, hanna-halman requested changes

2021-02-19 19:33 UTC, hanna-halman commented on src/main/java/pl/techlab24/OSKManager/model/validation/RideValidator.java
> -        }
Please remove validateCourseClient method

2021-02-19 22:18 UTC, hanna-halman approved these changes

2021-02-19 22:43 UTC, kmo2008 approved these changes

2021-02-19 22:46 UTC, merged